### ISSUE TITLE
Please remove me from the rubyheroes.com site and all future promotional materials

### ISSUE THREAD

**Issue by practicingruby** [rubyheroes/rubyheroes.com#5]
I no longer want to be associated (even indirectly) with this program.

Thanks.

**Comment by practicingruby** [comment]
Thank you.

**Comment by practicingruby** [comment]
I assume you're also going to deploy this soon? I still see my picture on the site.

**Comment by olivierlacan** [comment]
[![image](https://cloud.githubusercontent.com/assets/65950/14385209/31b23300-fd6d-11e5-8271-923086e77590.png)](https://rubyheroes.com/heroes/2010)

**Comment by practicingruby** [comment]
Thanks! All set, then. Make sure to keep this in mind in future presentations at RailsConf as well.
